package app;

import java.awt.Graphics;
import java.awt.Graphics2D;
import java.util.List;

public class SimplePaint extends javax.swing.JFrame {

	private final String[] command = { "Black", "Line" };
	private final BackendPaint bPaint;
	private int startX = -1;
	private int startY = -1;

	public SimplePaint(String username) {
		initComponents();
		initFrame();
		bPaint = new BackendPaint(username);
		paintPanel.paint(paintPanel.getGraphics());
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed"
	// desc="Generated Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		jButton3 = new javax.swing.JButton();
		jButton2 = new javax.swing.JButton();
		jButton1 = new javax.swing.JButton();
		paintPanel = new javax.swing.JPanel() {
			@Override
			public void paint(Graphics g) {
				super.paint(g);
				for (app.Shape s : bPaint.getList()) {
					bPaint.drawShape(s, g);
				}
			}
		};
		jButton4 = new javax.swing.JButton();
		jComboBox1 = new javax.swing.JComboBox<>();
		zoomButton = new javax.swing.JButton();
		colorChangeButton = new javax.swing.JButton();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

		jButton3.setText("Rectangle");
		jButton3.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton3ActionPerformed(evt);
			}
		});

		jButton2.setText("Circle");
		jButton2.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton2ActionPerformed(evt);
			}
		});

		jButton1.setText("Line");
		jButton1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton1ActionPerformed(evt);
			}
		});

		paintPanel.setBackground(java.awt.Color.white);
		paintPanel.setPreferredSize(new java.awt.Dimension(500, 500));
		paintPanel.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mousePressed(java.awt.event.MouseEvent evt) {
				paintPanelMousePressed(evt);
			}

			public void mouseReleased(java.awt.event.MouseEvent evt) {
				paintPanelMouseReleased(evt);
			}

			public void mouseClicked(java.awt.event.MouseEvent evt) {
				List<Shape> list = DatabaseConnectivity
						.getPaints(bPaint.username);
				int x = evt.getX();
				int y = evt.getY();
				for (int i = 0; i < list.size(); i++) {
					if (list.get(i).getModelShape().equals("Rectangle")) {
						if (list.get(i).rectangleContain(x, y)) {

							bPaint.drawRectangle(list.get(i).getStartX(), list
									.get(i).getStartY(), list.get(i).getEndX(),
									list.get(i).getEndY(), BackendPaint
											.changeColor(command[0],
													paintPanel.getGraphics()));

						}

					} else if (list.get(i).getModelShape().equals("Line")) {

						if (list.get(i).ptLineDistSq(x, y)) {

							BackendPaint.changeColor(command[0],
									paintPanel.getGraphics()).drawLine(
									list.get(i).getStartX(),
									list.get(i).getStartY(),
									list.get(i).getEndX(),
									list.get(i).getEndY());
						}

					} else if (list.get(i).getModelShape().equals("Circle")) {
						if (list.get(i).circleCotain(x, y)) {

							bPaint.drawCircle(list.get(i).getStartX(), list
									.get(i).getStartY(), list.get(i).getEndX(),
									list.get(i).getEndY(), BackendPaint
											.changeColor(command[0],
													paintPanel.getGraphics()));
						}
					}
				}

			}
		});

		javax.swing.GroupLayout paintPanelLayout = new javax.swing.GroupLayout(
				paintPanel);
		paintPanel.setLayout(paintPanelLayout);
		paintPanelLayout.setHorizontalGroup(paintPanelLayout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGap(0, 500, Short.MAX_VALUE));
		paintPanelLayout.setVerticalGroup(paintPanelLayout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addGap(0, 500,
				Short.MAX_VALUE));

		jButton4.setText("Exit");
		jButton4.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton4ActionPerformed(evt);
			}
		});

		jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(
				new String[] { "Black", "Red", "Green", "Blue" }));
		jComboBox1.addItemListener(new java.awt.event.ItemListener() {
			public void itemStateChanged(java.awt.event.ItemEvent evt) {
				jComboBox1ItemStateChanged(evt);
			}
		});

		zoomButton.setText("Zoom");
		zoomButton.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				zoomButtonActionPerformed(evt);
			}
		});

		colorChangeButton.setText("Change Color");
		colorChangeButton
				.addActionListener(new java.awt.event.ActionListener() {
					public void actionPerformed(java.awt.event.ActionEvent evt) {
						colorChangeButtonActionPerformed(evt);
					}
				});

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(
						layout.createSequentialGroup()
								.addContainerGap()
								.addComponent(paintPanel,
										javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addGap(18, 18, 18)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.LEADING,
												false)
												.addComponent(
														jButton1,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														Short.MAX_VALUE)
												.addComponent(
														jButton2,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														Short.MAX_VALUE)
												.addComponent(
														jButton3,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														Short.MAX_VALUE)
												.addComponent(
														jButton4,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														113, Short.MAX_VALUE)
												.addComponent(
														jComboBox1,
														0,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														Short.MAX_VALUE)
												.addComponent(
														zoomButton,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														Short.MAX_VALUE)
												.addComponent(
														colorChangeButton,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														Short.MAX_VALUE))
								.addContainerGap(
										javax.swing.GroupLayout.DEFAULT_SIZE,
										Short.MAX_VALUE)));
		layout.setVerticalGroup(layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(
						layout.createSequentialGroup()
								.addContainerGap()
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.LEADING,
												false)
												.addGroup(
														layout.createSequentialGroup()
																.addComponent(
																		jButton1)
																.addPreferredGap(
																		javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																.addComponent(
																		jButton2)
																.addPreferredGap(
																		javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																.addComponent(
																		jButton3)
																.addGap(18, 18,
																		18)
																.addComponent(
																		jComboBox1,
																		javax.swing.GroupLayout.PREFERRED_SIZE,
																		javax.swing.GroupLayout.DEFAULT_SIZE,
																		javax.swing.GroupLayout.PREFERRED_SIZE)
																.addGap(228,
																		228,
																		228)
																.addComponent(
																		colorChangeButton)
																.addPreferredGap(
																		javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																.addComponent(
																		zoomButton)
																.addGap(18, 18,
																		18)
																.addComponent(
																		jButton4))
												.addComponent(
														paintPanel,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.PREFERRED_SIZE))
								.addContainerGap(
										javax.swing.GroupLayout.DEFAULT_SIZE,
										Short.MAX_VALUE)));

		pack();
	}// </editor-fold>//GEN-END:initComponents

	private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton3ActionPerformed
		jButton1.setEnabled(true);
		jButton2.setEnabled(true);
		jButton3.setEnabled(false);
		command[1] = "Rectangle";
	}// GEN-LAST:event_jButton3ActionPerformed

	private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton2ActionPerformed
		jButton1.setEnabled(true);
		jButton2.setEnabled(false);
		jButton3.setEnabled(true);
		command[1] = "Circle";
	}// GEN-LAST:event_jButton2ActionPerformed

	private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton1ActionPerformed
		jButton1.setEnabled(false);
		jButton2.setEnabled(true);
		jButton3.setEnabled(true);
		command[1] = "Line";
	}// GEN-LAST:event_jButton1ActionPerformed

	private void paintPanelMousePressed(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_paintPanelMousePressed

		startX = evt.getX();
		startY = evt.getY();
	}// GEN-LAST:event_paintPanelMousePressed

	private void paintPanelMouseReleased(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_paintPanelMouseReleased

		Shape shape = new Shape(startX, startY, evt.getX(), evt.getY(),
				command[0], command[1]);

		bPaint.drawShape(shape, paintPanel.getGraphics());

	}// GEN-LAST:event_paintPanelMouseReleased

	private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton4ActionPerformed

		if (bPaint.exitConfirm()) {
			dispose();
		}
	}// GEN-LAST:event_jButton4ActionPerformed

	private void jComboBox1ItemStateChanged(java.awt.event.ItemEvent evt) {// GEN-FIRST:event_jComboBox1ItemStateChanged

		command[0] = jComboBox1.getItemAt(jComboBox1.getSelectedIndex());
	}// GEN-LAST:event_jComboBox1ItemStateChanged

	private void colorChangeButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_colorChangeButtonActionPerformed
		// TODO add your handling code here:
		// MouseListener[] e= paintPanel.getMouseListeners();

		command[1] = "";

	}// GEN-LAST:event_colorChangeButtonActionPerformed

	private void zoomButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_zoomButtonActionPerformed

		command[1] = "";
		Graphics2D g = (Graphics2D) paintPanel.getGraphics();
		g.translate(1000, 1000);
		g.scale(10.0, 10.0);
		repaint();

	}// GEN-LAST:event_zoomButtonActionPerformed

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JButton colorChangeButton;
	private javax.swing.JButton jButton1;
	private javax.swing.JButton jButton2;
	private javax.swing.JButton jButton3;
	private javax.swing.JButton jButton4;
	private javax.swing.JComboBox<String> jComboBox1;
	private javax.swing.JPanel paintPanel;
	private javax.swing.JButton zoomButton;

	// End of variables declaration//GEN-END:variables
	private void initFrame() {
		setResizable(false);
		setLocationRelativeTo(null);
		jButton1.setEnabled(false);
	}
}
